---
title: "Modeling Prac 3"
output: html_document
date: "2023-05-16"
---

```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
```


```{r}
a <- 0.4
b <- 1
r <- seq(0, 1, by = 0.01)

fecundity <- b * r^(1/2) # Fecundity
survival <- a * (1 - r^2) # Survival
```

```{r}
a2 <- 0.8
b2 <- 2

fecundity2 <- b2 * r^(1/2) # Fecundity with a & b doubled
survival2 <- a2 * (1 - r^2) # Survival with a & b doubled
```


```{r}
fitness <- data.frame(r, fecundity, survival, fecundity2, survival2)
```

```{r}
fitness <- pivot_longer(fitness, cols = 2:5, names_to = "measure", values_to = "value")
```

```{r}
fitness <- fitness %>% 
  mutate(f_or_s = ifelse(startsWith(measure, "fec"), "fecundity", "survival")) %>% 
  mutate(level = ifelse(endsWith(measure, "2"), "doubled", "baseline"))
```


```{r}
ggplot(data = fitness) +
  geom_line(aes(x = r, y = value, color = f_or_s, linetype = level)) +
  labs(x = "Reproductive effort (r)", y = "Fecundity F(r) or survival s(r)", color = "", linetype = "values of a and b")
```



```{r}
(1/(4*0.1))^(2/3)

(1/(4*0.9))^(2/3)
```






